---
title: 'Case Study: Prostheses'
author: "Yuxuan LI, Ariel Liang, Yuying TAN, "
date: "March 18, 2020"
fontsize: 12pt
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyhead[CO,CE]{LIANG(s2614693), LI(s2485265), TAN(s2586401)}
geometry: margin=0.8in
output: 
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plot3D)
```

## Introduction


## Data Preparation


```{r import data, include=TRUE}
# import data from Google Drive
URL <- "https://drive.google.com/uc?export=download&id=1crOKACRchddn5d7vV5aeASGAKuIw5diq"
DATA <- read.delim(URL, header=TRUE, sep="", dec=".")
```


```{r NA values, include=TRUE}
# import functions: pre_val() and post_val()
source("functions.R")

n_patient <- max(DATA$ID)
# substitute NA values with recent obs of the same patient
for (id in 1:n_patient)
{
  # extract patient data one by one
  data <- DATA[DATA$ID==id,]
  # operate while there're NA values
  if (sum(as.numeric(is.na(data$nMTPM)))>0)
  {
    row_na_list <- which(is.na(data$nMTPM))
    for (row_na in row_na_list)
    {
      if (row_na==1)
      {
        # if the 1st obs is missing, substitute with subsequent values
        data$nMTPM[row_na] <- post_val(data$nMTPM, row_na + 1)
      } 
      else if (row_na==dim(data)[1])
      {
        # if the last obs is missing, substitute with previous values
        data$nMTPM[row_na] <- pre_val(data$nMTPM, row_na - 1)
      }
      else 
      {
        # in other cases, substitue NA with the average of recent obs
        a <- pre_val(data$nMTPM, row_na - 1)
        b <- post_val(data$nMTPM, row_na + 1)
        data$nMTPM[row_na] <- (a+b)/2
      }
    }
  }
  DATA <- rbind(DATA,data)
}

# check if there're any more NA values
k_row <- dim(DATA)[1]
data <- DATA[(k_row/2+1):k_row,]
if (sum(as.numeric(is.na(data)))==0)
{
  DATA <- data
  save(DATA, file="prostheses.RData")
  knitr::kable(DATA[1:10,], row.names=FALSE, align="lrcrcrrr", digits=4,
               caption="Data of the First Two Patients")
} else
{
  print("clean the data again.")
}

# remove redundant variables
rm(data, id, k_row, row_na, row_na_list, a, b)
```

## Exploratory Data Analysis



```{r visualization, include=TRUE}
load("prostheses.RData")

for (id in 1:n_patient)
{
  data <- DATA[DATA$ID==id,]
  x <- data$FU.Months
  y <- data$BMI
  z <- data$nMTPM
  if (id==1)
  {
    lines3D(x, y, z, col=data$Type, lty=data$Sex, 
            xlim=c(min(DATA$FU.Months),max(DATA$FU.Months)),
            ylim=c(min(DATA$BMI),max(DATA$BMI)),
            zlim=c(min(DATA$nMTPM),max(DATA$nMTPM)))
  } else
  {
    lines3D(x, y, z, col=data$Type, lty=data$Sex, add=TRUE)
  }
}

rm(data, id, x, y, z) # remove redundant variables
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
